# Generated by Django 3.1.3 on 2020-11-27 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('travelcompapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTravelInfo',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('primary_guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('passenger_user_id', models.UUIDField(default=uuid.uuid4)),
                ('flight_no', models.CharField(max_length=100)),
                ('airlines', models.CharField(max_length=200)),
                ('arr_arline_code', models.CharField(max_length=100)),
                ('dep_arline_code', models.CharField(max_length=100)),
                ('status_of_ticket', models.BooleanField()),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(blank=True)),
                ('comments', models.TextField()),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
