# Generated by Django 3.1.3 on 2020-11-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelcompapp', '0002_passengertravelinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
