# Generated by Django 3.1.3 on 2020-11-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelcompapp', '0003_auto_20201127_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengertravelinfo',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
