# Generated by Django 3.1.3 on 2020-11-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelcompapp', '0004_auto_20201127_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertravelinfo',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='passengertravelinfo',
            name='phone_number',
        ),
    ]
