# Generated by Django 3.1.3 on 2020-11-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelcompapp', '0006_passengertravelinfo_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengertravelinfo',
            name='no_of_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertravelinfo',
            name='no_of_kids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passengertravelinfo',
            name='passenger_user_id',
            field=models.CharField(max_length=100),
        ),
    ]
